name: AEON_WATCH
on:
  workflow_dispatch:

jobs:
  test_signal:
    runs-on: ubuntu-latest
    steps:
      - name: Send_Ping
        run: |
          curl -X POST "${{ secrets.MAKE_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"command": "PING", "status": "ONLINE"}'
